### ISSUE TITLE
Will upgrade support Airpods Pro? Thank you

### ISSUE THREAD

**Issue by vincentchyu** [boo-dev/AirPort#10]
Will upgrade support Airpods Pro? Thank you

**Comment by vincentchyu** [comment]
Waiting for you

**Comment by vincentchyu** [comment]
Waiting for you,the next day

**Comment by rainloreley** [comment]
@uncleyeung I think @boo-dev has some other things to do rather than checking issues every minute. It takes time until a dev sees an issue/request and fixes/implements it. Writing a message every day does not help.
